use_frameworks!

platform :ios, '8.0'

target 'LLDatePicker_Example' do
  pod 'LLDatePicker', :path => '../'

  target 'LLDatePicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
